#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me to another page with a "301 Moved Permanently" status code

# Install Nginx
apt-get update
apt-get -y install nginx

# Define the redirection configuration
SERVER_CONFIG="server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
    location /redirect_me {
        return 301 https://www.example.com/new_page;
    }
}"

# Apply the server configuration
echo "$SERVER_CONFIG" > /etc/nginx/sites-enabled/default

# Test Nginx configuration
nginx -t

# Reload Nginx to apply changes
systemctl reload nginx

