#!/usr/bin/env bash
# Configures Nginx to return a custom 404 page

# Install Nginx
apt-get update
apt-get -y install nginx

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Define server configuration with custom 404 page
SERVER_CONFIG="server {
   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.html;
   error_page 404 /404.html;
   location = /404.html {
      internal;
   }
}"

# Apply the server configuration
echo "$SERVER_CONFIG" > /etc/nginx/sites-available/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Test Nginx configuration
nginx -t

# Reload Nginx to apply changes
systemctl reload nginx

