#!/usr/bin/env bash
# Loops from 1 to 20 and displays:
#   "bad luck from China" for the 4th iteration
#   "bad luck from Japan" for the 9th iteration
#   "bad luck from Italy" for the 17th iteration
#   "Best School" for all other iterations

CNT=1
while [ $CNT -le 20 ]
do
	case $CNT in

	4)
		echo "$CNT"
		echo "bad luck from China"
		;;
	9)
		echo "$CNT"
		echo "bad luck from Japan"
		;;
	17)
		echo "$CNT"
		echo "bad luck from Italy"
		;;
	*)
		echo "$CNT"
		;;
	esac
	(( CNT++ ))
done
