#!/usr/bin/env bash
# Loops from 1 to 10 and displays:
#   "bad luck" for the 4th iteration
#   "good luck" for the 8th iteration
#   "Best School" for all other iterations

CNT=1
while [ $CNT -lt 21 ]
do
	echo "$CNT"

	if [ $CNT -eq 4 ];
	then
		echo "bad luck from China"
	elif [ $CNT -eq 9 ];
	then
		echo "bad luck from Japan"
	elif [ $CNT -eq 17 ];
	then
		echo "bad luck from Italy"
	fi

	(( CNT++ ))
done
